version: '3.9'
services:
  game_server:
    image: lugobots/server:${SERVER_VERSION:-latest}
    command: play --dev-mode --timer-mode=wait # --waiting-duration=20m --starting-mode=wait
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=game_server:5000" ]
      interval: 2s
      timeout: 5s
      retries: 100
      start_period: 10s
  player_home_01:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_02:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_03:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_04:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_05:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_06:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_07:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_08:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_09:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_10:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_11:
    image: pybot:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_away_01:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_02:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_03:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_04:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_05:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_06:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_07:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_08:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_09:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_10:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
  player_away_11:
    image: lugobots/the-dummies-go:latest
    depends_on:
      game_server:
        condition: service_healthy
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000

