# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import physics_pb2 as physics__pb2
import server_pb2 as server__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote.proto',
  package='lugo',
  syntax='proto3',
  serialized_options=b'Z!github.com/lugobots/lugo4go/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cremote.proto\x12\x04lugo\x1a\rphysics.proto\x1a\x0cserver.proto\"\x14\n\x12PauseResumeRequest\"\x11\n\x0fNextTurnRequest\"\x12\n\x10NextOrderRequest\"o\n\x0e\x42\x61llProperties\x12\x1d\n\x08position\x18\x01 \x01(\x0b\x32\x0b.lugo.Point\x12 \n\x08velocity\x18\x02 \x01(\x0b\x32\x0e.lugo.Velocity\x12\x1c\n\x06holder\x18\x03 \x01(\x0b\x32\x0c.lugo.Player\"\x82\x01\n\x10PlayerProperties\x12\x1d\n\x04side\x18\x01 \x01(\x0e\x32\x0f.lugo.Team.Side\x12\x0e\n\x06number\x18\x02 \x01(\r\x12\x1d\n\x08position\x18\x03 \x01(\x0b\x32\x0b.lugo.Point\x12 \n\x08velocity\x18\x04 \x01(\x0b\x32\x0e.lugo.Velocity\"\x83\x01\n\x0eGameProperties\x12\x0c\n\x04turn\x18\x01 \x01(\r\x12\x12\n\nhome_score\x18\x02 \x01(\r\x12\x12\n\naway_score\x18\x03 \x01(\r\x12\x16\n\x0e\x66rame_interval\x18\x04 \x01(\x03\x12#\n\nshot_clock\x18\x05 \x01(\x0b\x32\x0f.lugo.ShotClock\"\xcd\x01\n\x0f\x43ommandResponse\x12.\n\x04\x63ode\x18\x01 \x01(\x0e\x32 .lugo.CommandResponse.StatusCode\x12)\n\rgame_snapshot\x18\x02 \x01(\x0b\x32\x12.lugo.GameSnapshot\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\"N\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rINVALID_VALUE\x10\x01\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x02\x12\t\n\x05OTHER\x10\x63\"\x18\n\x16ResumeListeningRequest\"\x19\n\x17ResumeListeningResponse2\xdf\x03\n\x06Remote\x12@\n\rPauseOrResume\x12\x18.lugo.PauseResumeRequest\x1a\x15.lugo.CommandResponse\x12\x38\n\x08NextTurn\x12\x15.lugo.NextTurnRequest\x1a\x15.lugo.CommandResponse\x12:\n\tNextOrder\x12\x16.lugo.NextOrderRequest\x1a\x15.lugo.CommandResponse\x12@\n\x11SetBallProperties\x12\x14.lugo.BallProperties\x1a\x15.lugo.CommandResponse\x12\x44\n\x13SetPlayerProperties\x12\x16.lugo.PlayerProperties\x1a\x15.lugo.CommandResponse\x12@\n\x11SetGameProperties\x12\x14.lugo.GameProperties\x1a\x15.lugo.CommandResponse\x12S\n\x14ResumeListeningPhase\x12\x1c.lugo.ResumeListeningRequest\x1a\x1d.lugo.ResumeListeningResponseB#Z!github.com/lugobots/lugo4go/protob\x06proto3'
  ,
  dependencies=[physics__pb2.DESCRIPTOR,server__pb2.DESCRIPTOR,])



_COMMANDRESPONSE_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='lugo.CommandResponse.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_VALUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEADLINE_EXCEEDED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=3, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=620,
  serialized_end=698,
)
_sym_db.RegisterEnumDescriptor(_COMMANDRESPONSE_STATUSCODE)


_PAUSERESUMEREQUEST = _descriptor.Descriptor(
  name='PauseResumeRequest',
  full_name='lugo.PauseResumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=71,
)


_NEXTTURNREQUEST = _descriptor.Descriptor(
  name='NextTurnRequest',
  full_name='lugo.NextTurnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=90,
)


_NEXTORDERREQUEST = _descriptor.Descriptor(
  name='NextOrderRequest',
  full_name='lugo.NextOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=110,
)


_BALLPROPERTIES = _descriptor.Descriptor(
  name='BallProperties',
  full_name='lugo.BallProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='lugo.BallProperties.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='lugo.BallProperties.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='holder', full_name='lugo.BallProperties.holder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=223,
)


_PLAYERPROPERTIES = _descriptor.Descriptor(
  name='PlayerProperties',
  full_name='lugo.PlayerProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='lugo.PlayerProperties.side', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='lugo.PlayerProperties.number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='lugo.PlayerProperties.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='lugo.PlayerProperties.velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=356,
)


_GAMEPROPERTIES = _descriptor.Descriptor(
  name='GameProperties',
  full_name='lugo.GameProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turn', full_name='lugo.GameProperties.turn', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='home_score', full_name='lugo.GameProperties.home_score', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='away_score', full_name='lugo.GameProperties.away_score', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_interval', full_name='lugo.GameProperties.frame_interval', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shot_clock', full_name='lugo.GameProperties.shot_clock', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=490,
)


_COMMANDRESPONSE = _descriptor.Descriptor(
  name='CommandResponse',
  full_name='lugo.CommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='lugo.CommandResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_snapshot', full_name='lugo.CommandResponse.game_snapshot', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='lugo.CommandResponse.details', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMANDRESPONSE_STATUSCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=698,
)


_RESUMELISTENINGREQUEST = _descriptor.Descriptor(
  name='ResumeListeningRequest',
  full_name='lugo.ResumeListeningRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=724,
)


_RESUMELISTENINGRESPONSE = _descriptor.Descriptor(
  name='ResumeListeningResponse',
  full_name='lugo.ResumeListeningResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=751,
)

_BALLPROPERTIES.fields_by_name['position'].message_type = physics__pb2._POINT
_BALLPROPERTIES.fields_by_name['velocity'].message_type = physics__pb2._VELOCITY
_BALLPROPERTIES.fields_by_name['holder'].message_type = server__pb2._PLAYER
_PLAYERPROPERTIES.fields_by_name['side'].enum_type = server__pb2._TEAM_SIDE
_PLAYERPROPERTIES.fields_by_name['position'].message_type = physics__pb2._POINT
_PLAYERPROPERTIES.fields_by_name['velocity'].message_type = physics__pb2._VELOCITY
_GAMEPROPERTIES.fields_by_name['shot_clock'].message_type = server__pb2._SHOTCLOCK
_COMMANDRESPONSE.fields_by_name['code'].enum_type = _COMMANDRESPONSE_STATUSCODE
_COMMANDRESPONSE.fields_by_name['game_snapshot'].message_type = server__pb2._GAMESNAPSHOT
_COMMANDRESPONSE_STATUSCODE.containing_type = _COMMANDRESPONSE
DESCRIPTOR.message_types_by_name['PauseResumeRequest'] = _PAUSERESUMEREQUEST
DESCRIPTOR.message_types_by_name['NextTurnRequest'] = _NEXTTURNREQUEST
DESCRIPTOR.message_types_by_name['NextOrderRequest'] = _NEXTORDERREQUEST
DESCRIPTOR.message_types_by_name['BallProperties'] = _BALLPROPERTIES
DESCRIPTOR.message_types_by_name['PlayerProperties'] = _PLAYERPROPERTIES
DESCRIPTOR.message_types_by_name['GameProperties'] = _GAMEPROPERTIES
DESCRIPTOR.message_types_by_name['CommandResponse'] = _COMMANDRESPONSE
DESCRIPTOR.message_types_by_name['ResumeListeningRequest'] = _RESUMELISTENINGREQUEST
DESCRIPTOR.message_types_by_name['ResumeListeningResponse'] = _RESUMELISTENINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PauseResumeRequest = _reflection.GeneratedProtocolMessageType('PauseResumeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAUSERESUMEREQUEST,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.PauseResumeRequest)
  })
_sym_db.RegisterMessage(PauseResumeRequest)

NextTurnRequest = _reflection.GeneratedProtocolMessageType('NextTurnRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEXTTURNREQUEST,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.NextTurnRequest)
  })
_sym_db.RegisterMessage(NextTurnRequest)

NextOrderRequest = _reflection.GeneratedProtocolMessageType('NextOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEXTORDERREQUEST,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.NextOrderRequest)
  })
_sym_db.RegisterMessage(NextOrderRequest)

BallProperties = _reflection.GeneratedProtocolMessageType('BallProperties', (_message.Message,), {
  'DESCRIPTOR' : _BALLPROPERTIES,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.BallProperties)
  })
_sym_db.RegisterMessage(BallProperties)

PlayerProperties = _reflection.GeneratedProtocolMessageType('PlayerProperties', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERPROPERTIES,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.PlayerProperties)
  })
_sym_db.RegisterMessage(PlayerProperties)

GameProperties = _reflection.GeneratedProtocolMessageType('GameProperties', (_message.Message,), {
  'DESCRIPTOR' : _GAMEPROPERTIES,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.GameProperties)
  })
_sym_db.RegisterMessage(GameProperties)

CommandResponse = _reflection.GeneratedProtocolMessageType('CommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESPONSE,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.CommandResponse)
  })
_sym_db.RegisterMessage(CommandResponse)

ResumeListeningRequest = _reflection.GeneratedProtocolMessageType('ResumeListeningRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESUMELISTENINGREQUEST,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.ResumeListeningRequest)
  })
_sym_db.RegisterMessage(ResumeListeningRequest)

ResumeListeningResponse = _reflection.GeneratedProtocolMessageType('ResumeListeningResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESUMELISTENINGRESPONSE,
  '__module__' : 'remote_pb2'
  # @@protoc_insertion_point(class_scope:lugo.ResumeListeningResponse)
  })
_sym_db.RegisterMessage(ResumeListeningResponse)


DESCRIPTOR._options = None

_REMOTE = _descriptor.ServiceDescriptor(
  name='Remote',
  full_name='lugo.Remote',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=754,
  serialized_end=1233,
  methods=[
  _descriptor.MethodDescriptor(
    name='PauseOrResume',
    full_name='lugo.Remote.PauseOrResume',
    index=0,
    containing_service=None,
    input_type=_PAUSERESUMEREQUEST,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NextTurn',
    full_name='lugo.Remote.NextTurn',
    index=1,
    containing_service=None,
    input_type=_NEXTTURNREQUEST,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NextOrder',
    full_name='lugo.Remote.NextOrder',
    index=2,
    containing_service=None,
    input_type=_NEXTORDERREQUEST,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetBallProperties',
    full_name='lugo.Remote.SetBallProperties',
    index=3,
    containing_service=None,
    input_type=_BALLPROPERTIES,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetPlayerProperties',
    full_name='lugo.Remote.SetPlayerProperties',
    index=4,
    containing_service=None,
    input_type=_PLAYERPROPERTIES,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetGameProperties',
    full_name='lugo.Remote.SetGameProperties',
    index=5,
    containing_service=None,
    input_type=_GAMEPROPERTIES,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResumeListeningPhase',
    full_name='lugo.Remote.ResumeListeningPhase',
    index=6,
    containing_service=None,
    input_type=_RESUMELISTENINGREQUEST,
    output_type=_RESUMELISTENINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTE)

DESCRIPTOR.services_by_name['Remote'] = _REMOTE

# @@protoc_insertion_point(module_scope)
